import { useState, useEffect, useCallback, useRef } from 'react';
import { createPortal } from 'react-dom';

/* ─────────────────────────────────────────
   PROJECT DATA
───────────────────────────────────────── */
const projects = [
  /* ── 1. Top/Featured Projects ── */
  {
    id: 2,
    title: 'AskMyDocs',
    categories: ['RAG & AI Apps'],
    shortDesc: 'Production-grade RAG system combining hybrid retrieval, cross-encoder reranking, and Groq Llama-3.3-70B with a Ragas evaluation CI gate.',
    fullDesc: 'A production-grade RAG system combining hybrid retrieval (pgvector dense search + PostgreSQL full-text search, fused via Reciprocal Rank Fusion) with cross-encoder reranking for precision. Documents are split using semantic and parent-child chunking, embedded locally with BAAI/bge-small-en-v1.5, and answers are generated by Groq\'s Llama-3.3-70B with enforced source citations. A Ragas evaluation gate (faithfulness, relevance, precision, recall) runs in CI to catch quality regressions before deploy.',
    tags: ['RAG', 'Hybrid Search', 'FastAPI', 'pgvector', 'Groq Llama-3.3', 'Cross-Encoder Reranking'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/askmydocs.png',
    videoUrl: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20video/askmydocs.mp4',
    githubUrl: 'https://github.com/mirza-shafi/AskMyDocs',
    demoUrl: 'https://askmydocs.mirzashafi.com/',
    featured: true,
  },
  {
    id: 105,
    title: 'AutofyBit RAG Chatbot',
    categories: ['RAG & AI Apps'],
    shortDesc: 'Production RAG chatbot utilizing pgvector semantic search and GPT-4o-mini to generate answers strictly grounded in official documentation.',
    fullDesc: 'A production RAG chatbot built for AutofyBit\'s customer support. AutofyBit\'s documentation, feature guides, and pricing sheets are chunked and embedded with OpenAI\'s text-embedding-3-small, then stored in a pgvector database. On each query, the system retrieves the most relevant chunks via semantic search and passes them as context to GPT-4o-mini, which generates an answer grounded in the actual docs instead of guessing. Built as a fully custom FastAPI pipeline — no low-code tools — so it scales cleanly as AutofyBit adds new products or updates pricing.',
    tags: ['RAG', 'FastAPI', 'GPT-4o-mini', 'pgvector', 'OpenAI Embeddings', 'Semantic Search'],
    image: null,
    gradient: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    icon: '💬',
    videoUrl: null,
    githubUrl: null,
    demoUrl: null,
    featured: true,
  },
  {
    id: 4,
    title: 'Heart Disease Prediction API',
    categories: ['AI/ML Engineering'],
    shortDesc: 'Production-grade FastAPI service serving a Random Forest classifier with SHAP explanations, Celery/Redis async batching, and Pytest integration.',
    fullDesc: 'A production-grade FastAPI service serving a Random Forest classifier for heart disease risk prediction, with SHAP-based feature explanations for every result. Built with JWT authentication, PostgreSQL persistence (SQLAlchemy + Alembic migrations), Celery/Redis for async batch predictions, and Redis caching with rate limiting on prediction endpoints. Includes structured JSON logging for production observability and a full Pytest integration suite with isolated transactional tests.',
    tags: ['FastAPI', 'scikit-learn', 'SHAP', 'PostgreSQL', 'Celery', 'Redis'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/heart_disease_prediction_picture.png',
    gradient: 'linear-gradient(135deg, #1a0a0a 0%, #2d0f0f 50%, #1a1a0a 100%)',
    icon: '❤️',
    videoUrl: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20video/heart%20disease%20prediction%20api.mp4',
    githubUrl: 'https://github.com/mirza-shafi/Heart-Disease-Prediction',
    demoUrl: 'https://heartdisease.mirzashafi.com/docs',
    featured: true,
  },
  {
    id: 5,
    title: 'Virtual Try-On System',
    categories: ['AI/ML Engineering'],
    shortDesc: 'CV pipeline for virtual clothing try-on via text prompts, using Segformer for semantic segmentation and Stable Diffusion Inpainting.',
    fullDesc: 'A CV pipeline where users upload a photo and describe an outfit via text prompt. Segformer B2 performs semantic clothing segmentation to isolate the upper or lower body region, then Stable Diffusion Inpainting generates a photorealistic new garment in that masked area. A Gradio dashboard visualizes every step — original photo, segmentation mask, region overlay, and final result — and the full pipeline is Dockerized with GPU support.',
    tags: ['Segformer', 'Stable Diffusion Inpainting', 'Gradio', 'PyTorch', 'Docker'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/vertual_try_on_system.png',
    gradient: 'linear-gradient(135deg, #0d0a1a 0%, #1a0d2e 50%, #0a1a2e 100%)',
    icon: '👕',
    videoUrl: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20video/vertual_try_on_system.mp4',
    githubUrl: 'https://github.com/mirza-shafi/Virtual-Try-On-System',
    demoUrl: null,
    featured: true,
  },
  {
    id: 3,
    title: 'Hospital RAG Assistant',
    categories: ['RAG & AI Apps'],
    shortDesc: 'Patient-facing AI assistant grounded in live hospital data using parent-child RAG with MongoDB Atlas Vector Search and Llama-3.1.',
    fullDesc: 'A patient-facing AI assistant for HealingWave, grounded entirely in the hospital portal\'s live data — doctors, appointments, blood stock, and medicines — using parent-child RAG with MongoDB Atlas Vector Search. Questions are embedded with a Hugging Face sentence-transformer, matched against indexed chunks, then expanded to full parent records before Llama-3.1-8B generates a cited, guardrailed answer. The index auto-rebuilds whenever admin data changes, and a rule-based fallback keeps the assistant responsive even if the LLM call fails.',
    tags: ['RAG', 'MongoDB Atlas Vector Search', 'Parent-Child Retrieval', 'Hugging Face', 'Llama 3.1'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/hmp_rag_chatbot.png',
    videoUrl: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20video/hmp_rag_chatbot.mp4',
    githubUrl: 'https://github.com/mirza-shafi/Hospital_Management_Portal',
    demoUrl: 'https://hmp.mirzashafi.com/',
    featured: true,
  },
  {
    id: 6,
    title: 'Local SLM Benchmark Suite',
    categories: ['AI/ML Engineering'],
    shortDesc: 'Full-stack privacy-first benchmarking suite for evaluating and comparing small language models (SLMs) on local hardware.',
    fullDesc: 'A full-stack benchmarking suite for comparing small language models (TinyLlama, Phi-2, Mistral-7B) entirely on local hardware. A FastAPI backend loads models via Transformers and PyTorch (with M1 Metal acceleration) and measures real latency, throughput, and memory per inference. A React + TypeScript frontend renders side-by-side outputs with semantic similarity scoring and cost/energy estimates — built for privacy-conscious teams evaluating SLMs before committing to production.',
    tags: ['FastAPI', 'React', 'TypeScript', 'PyTorch', 'Transformers'],
    image: '/images/project_slm.png',
    videoUrl: null,
    githubUrl: 'https://github.com/mirza-shafi/local-slm-benchmark-suite',
    demoUrl: null,
    featured: true,
  },

  /* ── 2. Other Projects ── */
  {
    id: 101,
    title: 'Facebook Lead Automation (Autofy Solution)',
    categories: ['AI Automation'],
    shortDesc: 'Automates 50+ daily Facebook leads directly into the Autofy CRM via n8n, saving hours of manual data entry.',
    fullDesc: 'I built an automated lead generation pipeline for Autofy Solutions entirely on n8n. It listens for incoming leads from Facebook Lead Ads via webhooks and posts them directly into their internal CRM. Currently automating 50+ leads daily, this simple yet powerful solution eliminates manual tracking and saves significant time for the team.',
    tags: ['n8n', 'Facebook Ads', 'CRM', 'Webhooks', 'Automation'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/facebook_lead_automation.png',
    gradient: 'linear-gradient(135deg, #1d4ed8 0%, #1e40af 100%)',
    icon: '⚡',
    videoUrl: null,
    githubUrl: null,
    demoUrl: null,
    featured: false,
  },
  {
    id: 102,
    title: 'Personal AI News Agent',
    categories: ['AI Automation'],
    shortDesc: 'Custom n8n agent that fetches AI news daily, summarizes it using Groq LLM, and emails a personalized newsletter at 7 AM.',
    fullDesc: 'A personal automation agent acting as an intelligent news aggregator. Triggered daily at 7 AM via n8n, it fetches the latest AI news and tools from across the web. It uses a Groq-powered Chat Model to deduplicate and summarize the articles, generates a clean HTML newsletter, and automatically distributes it via Gmail. The system also manages subscriber lists natively via Google Sheets.',
    tags: ['n8n', 'Groq', 'LLM', 'Gmail API', 'Google Sheets', 'Automation'],
    image: '/images/project_ai_news.png',
    gradient: null,
    icon: null,
    videoUrl: null,
    githubUrl: null,
    demoUrl: null,
    featured: false,
  },
  {
    id: 103,
    title: 'AI Article Agent',
    categories: ['AI Automation'],
    shortDesc: 'FastAPI-driven workflow that scrapes web articles, summarizes them via Gemini AI, logs to Google Sheets, and emails the report.',
    fullDesc: 'An end-to-end AI article summarization pipeline. Users submit article URLs through a custom FastAPI web application, which triggers an n8n automation workflow via webhook. The n8n pipeline orchestrates web scraping, cleans the raw text, and leverages Google Gemini for summarization and insight extraction. The final processed data is automatically archived in a Google Sheet database and emailed directly to the user as a formatted report.',
    tags: ['FastAPI', 'n8n', 'Gemini AI', 'Web Scraping', 'Google Sheets', 'Gmail API', 'Python'],
    image: '/images/project_ai_article.png',
    gradient: null,
    icon: null,
    videoUrl: null,
    githubUrl: null,
    demoUrl: null,
    featured: false,
  },
  {
    id: 104,
    title: 'CRM & Omnichannel AI Agent (Autofy Solution)',
    categories: ['AI Automation'],
    shortDesc: 'Custom React CRM integrating WhatsApp & Messenger, featuring a trained AI agent that takes over conversations when staff are away.',
    fullDesc: 'Developed a comprehensive omnichannel CRM platform for Autofy Solutions, featuring a React-based unified inbox for staff to seamlessly communicate with customers across WhatsApp and Messenger. The backend routing and automation logic are orchestrated using robust n8n workflows. To ensure 24/7 engagement, a custom-trained AI agent automatically takes over conversations when human agents are unavailable, providing context-aware replies based on company data. The system utilizes PostgreSQL for storing chat histories, Redis for real-time performance and session management, and Cloudflare R2 for secure storage of media files and documents.',
    tags: ['React', 'n8n', 'PostgreSQL', 'Redis', 'Cloudflare R2', 'WhatsApp API', 'Messenger API', 'Custom AI Agent'],
    image: '/images/project_autofy_crm.png',
    gradient: null,
    icon: null,
    videoUrl: null,
    githubUrl: null,
    demoUrl: null,
    featured: false,
  },
  {
    id: 301,
    title: 'Hospital Management Portal',
    categories: ['Full-Stack'],
    shortDesc: 'Comprehensive MERN stack hospital management system featuring multi-role portals, a RAG-powered AI assistant, and an analytics dashboard.',
    fullDesc: 'A comprehensive hospital management system built on the MERN stack, with multi-role portals (admin, doctor, patient) for appointments, blood bank inventory, pharmacy stock, ward/cabin booking, and billing. Includes a RAG-powered AI assistant that answers questions from the portal\'s own live data using semantic vector search — plus an analytics dashboard with Chart.js visualizations. JWT-secured, role-based access control, fully Dockerized for deployment.',
    tags: ['MERN', 'MongoDB', 'React', 'Node.js', 'RAG', 'Docker'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/hmp_website.png',
    videoUrl: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20video/hmp_website.mp4',
    githubUrl: 'https://github.com/mirza-shafi/Hospital_Management_Portal',
    demoUrl: 'https://hmp.mirzashafi.com/',
    featured: false,
  },
  {
    id: 7,
    title: 'TaskFlow',
    categories: ['Full-Stack'],
    shortDesc: 'Full-stack productivity suite featuring task management, habit tracking, and team workspaces built with FastAPI, React, and MongoDB.',
    fullDesc: 'A full-stack productivity suite combining task management, notes, habit tracking, and team workspaces. Backend built with FastAPI and MongoDB Atlas (Motor async driver); frontend in React + TypeScript with Shadcn UI and TanStack Query. Authentication uses a dual JWT (access/refresh) system with Argon2 hashing, Firebase Google OAuth, and cross-device session management. Habit tracking includes GitHub-style heatmaps and streak analytics, while team workspaces support role-based permissions and activity logs. Fully Dockerized with optimized production images.',
    tags: ['FastAPI', 'React', 'TypeScript', 'MongoDB', 'JWT', 'Docker'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/taskflow.png',
    videoUrl: null,
    githubUrl: 'https://github.com/mirza-shafi/TaskFlow',
    demoUrl: 'https://task-flow.mirzashafi.com/',
    featured: false,
  },
  {
    id: 8,
    title: 'StuRent',
    categories: ['Full-Stack'],
    shortDesc: 'Student rental marketplace for housing and equipment built with Django REST Framework, React, and PostgreSQL.',
    fullDesc: 'A student rental marketplace built with Django REST Framework and React. Supports housing listings (rent/buy/both) with dynamic property attributes, monthly billing with automatic security deposit calculation, and equipment rental alongside peer-to-peer buying/selling. Includes direct messaging between tenants and landlords, Google OAuth login, an admin approval workflow for listings, and a KPI dashboard tracking revenue and transaction volume. JWT auth with silent token refresh.',
    tags: ['Django REST Framework', 'React', 'PostgreSQL', 'JWT'],
    image: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20picture/sturent_picture.png',
    gradient: 'linear-gradient(135deg, #0a0d1a 0%, #0f1628 50%, #0a1a0f 100%)',
    icon: '🎓',
    videoUrl: 'https://pub-2e228f0de4e14489b5acc58b8a133c05.r2.dev/project%20video/sturent.mp4',
    githubUrl: 'https://github.com/mirza-shafi/Sturent',
    demoUrl: 'https://sturent.mirzashafi.com/',
    featured: false,
  }
];

const CATEGORIES = [
  { key: 'All',              label: 'All' },
  { key: 'AI Automation',    label: '🤖 AI Automation' },
  { key: 'RAG & AI Apps',   label: '🧠 RAG & AI Apps' },
  { key: 'AI/ML Engineering',label: '⚡ AI/ML Engineering' },
  { key: 'Full-Stack',       label: '🌐 Full-Stack' },
];

const INITIAL_COUNT = 6;
const VISIBLE_TAGS = 3;

/* ─────────────────────────────────────────
   ICONS
───────────────────────────────────────── */
const CloseIcon = () => (
  <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" viewBox="0 0 24 24">
    <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);
const GithubIcon = () => (
  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24">
    <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22" />
  </svg>
);
const ExternalIcon = () => (
  <svg width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24">
    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
    <polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" />
  </svg>
);
const SparkleIcon = () => (
  <svg width="13" height="13" fill="currentColor" viewBox="0 0 24 24">
    <path d="M12 2l2.09 6.26L21 10l-6.91 1.74L12 18l-2.09-6.26L3 10l6.91-1.74z" />
  </svg>
);
const ChevronDown = () => (
  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" viewBox="0 0 24 24">
    <path d="m6 9 6 6 6-6" />
  </svg>
);
const ChevronUp = () => (
  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" viewBox="0 0 24 24">
    <path d="m18 15-6-6-6 6" />
  </svg>
);

/* ─────────────────────────────────────────
   CARD THUMBNAIL — image or gradient placeholder
───────────────────────────────────────── */
function CardThumb({ project, isHovered }) {
  const videoRef = useRef(null);

  useEffect(() => {
    if (isHovered && videoRef.current) {
      videoRef.current.play().catch(() => {});
    } else if (!isHovered && videoRef.current) {
      videoRef.current.pause();
    }
  }, [isHovered]);

  if (project.image) {
    return (
      <div className="proj-thumb">
        <img src={project.image} alt={project.title} className="proj-thumb-img" loading="lazy" />
        {project.videoUrl && (
          <video 
            ref={videoRef}
            src={project.videoUrl}
            className={`proj-thumb-video ${isHovered ? 'playing' : ''}`}
            muted 
            loop 
            playsInline
          />
        )}
        {project.videoUrl && (
          <div className="proj-play-badge">
            <svg width="32" height="32" fill="rgba(255,255,255,0.9)" viewBox="0 0 24 24"><path d="M8 5v14l11-7z" /></svg>
          </div>
        )}
        {project.featured && <span className="proj-featured-badge">Featured</span>}
        <span className="proj-category-badge">{project.categories[0]}</span>
        <div className="proj-thumb-overlay" />
      </div>
    );
  }

  // Gradient placeholder for projects without screenshots yet
  return (
    <div className="proj-thumb" style={{ background: project.gradient || 'linear-gradient(135deg,#111,#222)' }}>
      <div className="proj-placeholder-content">
        <span className="proj-placeholder-icon">{project.icon || '🚀'}</span>
        <span className="proj-placeholder-label">{project.title}</span>
      </div>
      {project.featured && <span className="proj-featured-badge">Featured</span>}
      <span className="proj-category-badge">{project.categories[0]}</span>
    </div>
  );
}

/* ─────────────────────────────────────────
   PROJECT CARD
───────────────────────────────────────── */
function ProjectCard({ project, onClick }) {
  const [isHovered, setIsHovered] = useState(false);
  const visibleTags = project.tags.slice(0, VISIBLE_TAGS);
  const extraCount = project.tags.length - VISIBLE_TAGS;

  return (
    <div className="proj-card" 
      onClick={() => onClick(project)} 
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      role="button" tabIndex={0}
      onKeyDown={e => e.key === 'Enter' && onClick(project)}>
      <CardThumb project={project} isHovered={isHovered} />
      <div className="proj-info">
        <h3 className="proj-title">{project.title}</h3>
        <p className="proj-desc">{project.shortDesc}</p>
        <div className="proj-tags">
          {visibleTags.map(tag => <span key={tag} className="proj-tag">{tag}</span>)}
          {extraCount > 0 && <span className="proj-tag proj-tag-extra">+{extraCount}</span>}
        </div>
      </div>
    </div>
  );
}

/* ─────────────────────────────────────────
   MODAL
───────────────────────────────────────── */
function ProjectModal({ project, onClose }) {
  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', handler);
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', handler);
      document.body.style.overflow = '';
    };
  }, [onClose]);

  const previewUrl = project.demoUrl && project.demoUrl !== '#'
    ? project.demoUrl.replace('https://', '')
    : 'localhost:3000';

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-panel" onClick={e => e.stopPropagation()}>

        <button className="modal-close" onClick={onClose} aria-label="Close"><CloseIcon /></button>

        {/* Browser mockup */}
        <div className="modal-preview">
          <div className="browser-bar">
            <div className="browser-dots">
              <span className="bdot bdot-red" /><span className="bdot bdot-yellow" /><span className="bdot bdot-green" />
            </div>
            <div className="browser-url">{previewUrl}</div>
          </div>
          <div className="modal-media">
            {project.videoUrl ? (
              <video src={project.videoUrl} controls autoPlay muted playsInline className="modal-video" />
            ) : project.image ? (
              <img src={project.image} alt={project.title} className="modal-img" />
            ) : (
              <div className="modal-placeholder" style={{ background: project.gradient }}>
                <span className="modal-placeholder-icon">{project.icon || '🚀'}</span>
                <span className="modal-placeholder-hint">Video coming soon</span>
              </div>
            )}
          </div>
        </div>

        {/* Info */}
        <div className="modal-info">
          <div className="modal-info-header">
            <h2 className="modal-title">{project.title}</h2>
            <div className="modal-badges">
              {project.featured && (
                <span className="modal-featured-badge"><SparkleIcon /> Featured Project</span>
              )}
              {project.categories.map(cat => (
                <span key={cat} className="modal-cat-badge">{cat}</span>
              ))}
            </div>
          </div>

          <p className="modal-full-desc">{project.fullDesc}</p>

          <div className="modal-tech">
            <h4 className="modal-tech-label">Technologies Used</h4>
            <div className="modal-tags">
              {project.tags.map(tag => <span key={tag} className="modal-tag">{tag}</span>)}
            </div>
          </div>

          <div className="modal-actions">
            <a href={project.githubUrl} target="_blank" rel="noreferrer" className="modal-btn modal-btn-source">
              <GithubIcon /> View Source
            </a>
            {project.demoUrl && project.demoUrl !== '#' && (
              <a href={project.demoUrl} target="_blank" rel="noreferrer" className="modal-btn modal-btn-demo">
                <ExternalIcon /> Live Demo
              </a>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}

/* ─────────────────────────────────────────
   MAIN EXPORT
───────────────────────────────────────── */
export default function Projects() {
  const [selected, setSelected] = useState(null);
  const [activeCategory, setActiveCategory] = useState('All');
  const [showAll, setShowAll] = useState(false);
  const close = useCallback(() => setSelected(null), []);

  const filtered = activeCategory === 'All'
    ? projects
    : projects.filter(p => p.categories.includes(activeCategory));

  const visible = showAll ? filtered : filtered.slice(0, INITIAL_COUNT);
  const hasMore = filtered.length > INITIAL_COUNT;

  const handleCategory = (key) => {
    setActiveCategory(key);
    setShowAll(false);
  };

  return (
    <div className="projects-section-inner">

      {/* Header */}
      <div className="proj-section-header">
        <span className="proj-badge"><SparkleIcon /> Featured Work</span>
        <h2 className="proj-section-title">
          AI Projects in <span className="proj-title-accent">Action</span>
        </h2>
        <p className="proj-section-sub">
          Real-world AI applications — from chatbot automation and RAG systems to computer vision and full-stack platforms
        </p>
      </div>

      {/* Category filter */}
      <div className="proj-filter-row">
        {CATEGORIES.map(({ key, label }) => {
          const count = key === 'All' ? projects.length : projects.filter(p => p.categories.includes(key)).length;
          return (
            <button
              key={key}
              className={`proj-filter-btn ${activeCategory === key ? 'proj-filter-btn--active' : ''}`}
              onClick={() => handleCategory(key)}
            >
              {label}
              <span className="proj-filter-count">{count}</span>
            </button>
          );
        })}
      </div>

      {/* Grid */}
      {visible.length > 0 ? (
        <div className="proj-grid">
          {visible.map(project => (
            <ProjectCard key={project.id} project={project} onClick={setSelected} />
          ))}
        </div>
      ) : (
        <div className="proj-empty">No projects in this category yet.</div>
      )}

      {/* Show more / less */}
      {hasMore && (
        <div className="proj-footer">
          <button className="proj-view-all-btn" onClick={() => setShowAll(prev => !prev)}>
            {showAll ? <><ChevronUp /> Show Less</> : <><ChevronDown /> View All {filtered.length} Projects</>}
          </button>
          {!showAll && (
            <p className="proj-explore-hint">Showing {visible.length} of {filtered.length} projects</p>
          )}
        </div>
      )}

      {selected && typeof document !== 'undefined' && createPortal(<ProjectModal project={selected} onClose={close} />, document.body)}
    </div>
  );
}
